spring:
  application:
    name: student-service
  cloud:
    config:
      uri:
      - http://localhost:8888
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
      
